repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
    -   id: double-quote-string-fixer
    -   id: name-tests-test
    -   id: requirements-txt-fixer


- repo: https://github.com/pre-commit/mirrors-eslint
  rev: v8.56.0  # Replace with latest stable
  hooks:
    - id: eslint
      language: node
      types: [ html ]
      additional_dependencies: [ 'eslint', 'eslint-plugin-html' ]

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.11.13
  hooks:
    # Run the linter.
    - id: ruff-check
      types_or: [ python, pyi ]
      args: [ --fix , "--target-version", "py311"]
    # Run the formatter.
    - id: ruff-format
      types_or: [ python, pyi ]
      args: [ --diff ]
