repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
        language_version: python3.12
    -   id: end-of-file-fixer
        language_version: python3.12
    -   id: check-yaml
        language_version: python3.12
    -   id: debug-statements
        language_version: python3.12
    -   id: double-quote-string-fixer
        language_version: python3.12
    -   id: name-tests-test
        language_version: python3.12
    -   id: requirements-txt-fixer
        language_version: python3.12

- repo: https://github.com/pre-commit/mirrors-eslint
  rev: v8.56.0
  hooks:
    - id: eslint
      language: node
      types: [ html ]
      additional_dependencies: [ 'eslint', 'eslint-plugin-html' ]
      # (no language_version here, it's node-based, not Python)

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      args: ["--profile", "black"]

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.13
  hooks:
    - id: ruff-check
      types_or: [ python, pyi ]
      args: [ --fix, "--target-version", "py311" ]
      language_version: python3.12
